name: Hello # 名前

# イベント　これはプッシュ時に発動
# 配列で複数指定することも可能
on: push 

# ジョブ内容
jobs: 
  hello: # ジョブのID。自由に命名可能
    runs-on: ubunts-latest # 実行環境にubuntuを指定

    steps: # ステップの定義
      - run: echo "Hello world" # シェルコマンドの実行
      - uses: actions/checkout@v4 # GithubActionsが用意している「アクション」を呼ぶ