name: Github Discussions Notifier

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
jobs:
  discussion_created:
    runs-on: ubuntu-latest
    if: github.event.discussion && !github.event.comment
    steps:
      - run: |
          curl -X POST -d '{ "text": "Created discussion: ${{ github.event.discussion.html_url }}" }' ${{ secrets.SLACK_WEBHOOK }}
  discussion_commented:
    runs-on: ubuntu-latest
    if: github.event.discussion && github.event.comment
    steps:
      - name: Send GitHub Action data to a Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: webhook-trigger