name: Github Discussions Notifier

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
jobs:
  discussion_created:
    runs-on: ubuntu-latest
    if: github.event.discussion && !github.event.comment
    steps:
      - run: |
          curl -X POST -d '{ "text": "Created discussion: ${{ github.event.discussion.html_url }}" }' ${{ secrets.SLACK_WEBHOOK }}
  discussion_commented:
    runs-on: ubuntu-latest
    if: github.event.discussion && github.event.comment
    steps:
      - name: Prepare payload
        id: prepare_payload
        run: |
          title=${{ github.event.discussion.title }}
          printf -v markdown_message_unescaped %b "*<${{ github.event.comment.html_url }}|Comment on $title>*\n ${{ github.event.comment.body}}"
      - name: Post a message in a channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: ${{ steps.prepare_payload.outputs.markdown_message_unescaped }}"


