name: Github Discussions Notifier

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
jobs:
  discussion_created:
    runs-on: ubuntu-latest
    if: github.event.discussion && !github.event.comment
    steps:
      - run: |
          curl -X POST -d '{ "text": "Created discussion: ${{ github.event.discussion.html_url }}" }' ${{ secrets.SLACK_WEBHOOK }}
  discussion_commented:
    runs-on: ubuntu-latest
    if: github.event.discussion && github.event.comment
    steps:
      - run: |
          COMMENT_BODY=$(echo "${{ github.event.comment.body }}" | cut -c 1-200)
          if [ ${#COMMENT_BODY} -eq 200 ]; then
           COMMENT_BODY="${COMMENT_BODY}..."
          fi
          curl -X POST -H "Content-Type: application/json" -d '{ "text": "Discussionsにコメントがつきました\n${{ github.event.comment.body }}\n${{ github.event.comment.html_url }}" }' ${{ secrets.SLACK_WEBHOOK }}
